site_name: CEH-IN-BULLET-POINTS

theme:
  name: material
  language: 'en'
  palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
        
  font:
    text: Barlow
    code: Roboto Mono
    
docs_dir: chapters
nav: 
  - Introduction:
    - Information security:
        - 'Information security overview' : './01-introduction/information-security-overview.md'
        - 'Security threats and attacks' : './01-introduction/security-threats-and-attacks.md'
        - 'Information security controls':
          - 'Information security controls overview' : './01-introduction/information-security-controls.md'
          - 'Risk management' : './01-introduction/risk-management.md'
          - 'Incident management' : './01-introduction/incident-management.md'
          - 'Network security' : './01-introduction/network-security.md'
          - 'Security policies' : './01-introduction/security-policies.md'
          - 'Physical security' : './01-introduction/physical-security.md'
          - 'Data leakage backup and recovery' : './01-introduction/data-leakage-backup-and-recovery.md'
          - 'Identity access management (IAM)' : './01-introduction/identity-access-management-(iam).md'
        - 'Threat intelligence and forensics' : './01-introduction/threat-intelligence-and-forensics.md'
        - 'Laws, standards and regulations' : './01-introduction/laws-standards-and-regulations.md'
    - Hacking:
        - 'Hacker types' : './01-introduction/hacker-types.md'
        - 'Hacking stages' : './01-introduction/hacking-stages.md'
    - Penetration testing:
        - 'Penetration testing overview' : './01-introduction/penetration-testing.md'
        - 'Penetration testing phases' : './01-introduction/penetration-testing-phases.md'
  - Footprinting:
    - 'Footprinting overview' : './02-footprinting/footprinting-overview.md'
    - 'Search engines and online resources' : './02-footprinting/search-engines-and-online-resources.md'
    - 'WHOIS, GeoIpLocation and DNS interrogation' : './02-footprinting/whois-geoiplocation-and-dns-interrogation.md'
    - 'Email footprinting' : './02-footprinting/email-footprinting.md'
    - 'Website footprinting' : './02-footprinting/website-footprinting.md'
    - 'Network footprinting' : './02-footprinting/network-footprinting.md'
  - Scanning networks:
    - 'Scanning networks overview' : './03-scanning-networks/scanning-networks-overview.md'
    - 'TCP/IP basics' : './03-scanning-networks/tcpip-basics.md'
    - 'Scanning tools' : './03-scanning-networks/scanning-tools.md'
    - 'Scanning techniques' : './03-scanning-networks/scanning-techniques.md'
    - 'Bypassing IDS and firewall' : './03-scanning-networks/bypassing-ids-and-firewall.md'
    - 'Banner grabbing' : './03-scanning-networks/banner-grabbing.md'
  - Enumeration:
    - 'Enumeration Overview' : './04-enumeration/enumeration-overview.md'
    - 'DNS enumeration' : './04-enumeration/dns-enumeration.md'
  - Vulnerabilities:
    - 'Vulnerability analysis' : './05-vulnerabilities/vulnerability-analysis.md'
    - 'Common vulnerabilities' : './05-vulnerabilities/common-vulnerabilities.md'
    - 'Automated penetration testing tools' : './05-vulnerabilities/automated-penetration-testing-tools.md'
  - System hacking:
    - Cracking passwords:
        - 'Cracking passwords overview' : './06-system-hacking/cracking-passwords-overview.md'
        - 'Microsoft authentication' : './06-system-hacking/microsoft-authentication.md'
        - 'Password cracking tools' : './06-system-hacking/password-cracking-tools.md'
    - 'Linux basics' : './06-system-hacking/linux-basics.md'
    - 'Escalating privileges' : './06-system-hacking/escalating-privileges.md'
    - 'Executing applications' : './06-system-hacking/executing-applications.md'
    - 'Hiding files' : './06-system-hacking/hiding-files.md'
    - 'Covering tracks' : './06-system-hacking/covering-tracks.md'
  - 'Malware overview':
    - 'Malware overview' : './07-malware/malware-overview.md'
    - 'Trojans' : './07-malware/trojans.md'
    - 'Viruses' : './07-malware/viruses.md'
    - 'Malware analysis' : './07-malware/malware-analysis.md'
  - 'Sniffing':
    - 'Sniffing overview' : './08-sniffing/sniffing-overview.md'
    - 'Sniffing tools' : './08-sniffing/sniffing-tools.md'
    - 'Sniffing attacks':
        - 'Sniffing attacks overview' : './08-sniffing/sniffing-attacks-overview.md'
        - 'Spoofing attacks' : './08-sniffing/spoofing-attacks.md'
        - 'ARP poisoning' : './08-sniffing/arp-poisoning.md'
  - 'Wireless networks':
    - 'Wireless networks overview' : './09-wireless-networks/wireless-networks-overview.md'
    - 'AAA protocols' : './09-wireless-networks/aaa-protocols.md'
    - 'Wireless threats and attacks' : './09-wireless-networks/wireless-threats-and-attacks.md'
    - 'Wireless security tools' : './09-wireless-networks/wireless-security-tools.md'
    - 'Bluetooth' : './09-wireless-networks/bluetooth.md'
  - 'Social engineering':
      - 'Social engineering overview' : './10-social-engineering/social-engineering-overview.md'
      - 'Social engineering types' : './10-social-engineering/social-engineering-types.md'
  - 'Firewalls IDS and Honeypots':
      - 'Intrusion detection system (IDS)':
        - 'Intrusion detection system (IDS) overview' : './11-firewalls-ids-and-honeypots/intrusion-detection-system-(ids)-overview.md'
        - 'Evading IDS' : './11-firewalls-ids-and-honeypots/evading-ids.md'
      - 'Firewall':
        - 'Firewall overview' : './11-firewalls-ids-and-honeypots/firewall-overview.md'
        - 'Evading firewalls' : './11-firewalls-ids-and-honeypots/evading-firewalls.md'
      - 'Honeypot' : './11-firewalls-ids-and-honeypots/honeypot.md'
  - 'Web servers':
      - 'Hacking web servers' : './12-web-servers/hacking-web-servers.md'
      - 'Web server threats and attacks' : './12-web-servers/web-server-threats-and-attacks.md'
  - 'Web applications':
      - 'Hacking web applications' : './13-web-applications/hacking-web-applications.md'
      - 'OWASP top 10 threats' : './13-web-applications/owasp-top-10-threats.md'
      - 'Denial of service' : './13-web-applications/denial-of-service.md'
      - 'Session hijacking' : './13-web-applications/session-hijacking.md'
  - 'SQL injection':
      - 'SQL injection overview' : './14-sql-injection/sql-injection-overview.md'
      - 'SQL injection types' : './14-sql-injection/sql-injection-types.md'
  - 'Cryptography':
      - 'Cryptography overview' : './15-cryptography/cryptography-overview.md'
      - 'Encryption algorithms' : './15-cryptography/encryption-algorithms.md'
      - 'Hashing algorithms' : './15-cryptography/hashing-algorithms.md'
      - 'Communication':
        - 'Encrypting communication' : './15-cryptography/encrypting-communication.md'
        - 'Tunneling protocols' : './15-cryptography/tunneling-protocols.md'
      - 'Encrypting disk' : './15-cryptography/encrypting-disk.md'
      - 'Cryptanalysis' : './15-cryptography/cryptanalysis.md'
  - 'Cloud':
      - 'Cloud computing' : './16-cloud-computing/cloud-computing.md'
      - 'Cloud security' : './16-cloud-computing/cloud-security.md'
      - 'Container security' : './16-cloud-computing/container-security.md'
  - 'Mobile platforms':
      - 'Mobile hacking' : './17-mobile-platforms/mobile-hacking.md'
      - 'Mobile attack vectors' : './17-mobile-platforms/mobile-attack-vectors.md'
      - 'Mobile attacks' : './17-mobile-platforms/mobile-attacks.md'
  - 'IoT and OT':
      - 'IoT hacking' : './18-iot-and-ot/iot-hacking.md'
      - 'IoT security' : './18-iot-and-ot/iot-security.md'
  - 'Exam readiness' : '19-exam-readiness/exam-readiness.md'
